scratch_root: ${oc.env:SCRATCH_ROOT}
dataset_root: ${oc.env:DATASET_ROOT}
project_root: ${oc.env:PROJECT_ROOT}
waymo_data_folder: ${dataset_root}/waymo_open_dataset_motion_v_1_1_0
waymo_train_folder: ${waymo_data_folder}/training
waymo_val_folder: ${waymo_data_folder}/validation
waymo_test_folder: ${waymo_data_folder}/testing

hydra:
  run:
    dir: ${project_root}/slurm_logs/${now:%Y.%m.%d}/${now:%H.%M.%S}/${hydra.job.override_dirname}

model_name: dm

defaults:
  - dataset_name: waymo
  - dataset@dm.dataset: waymo_dm
  - train@dm.train: waymo_dm
  - eval@dm.eval: waymo_dm
  - model@dm.model: waymo_dm
  - datamodule@dm.datamodule: waymo_dm
  - sim: base
  - _self_

dm:
  train:
    devices: 1
    track: True
    run_name: scenario_dreamer_dm_train
