# Fixed-map direct diffusion model training on Waymo.
#
# Usage:
#   python train.py --config-name config_dm_fixed_map_agent_goal_train

model_name: dm_fixed_map_agent_goal

defaults:
  - _base
  - dataset_name: waymo
  - dm_fixed_map_agent_goal/dataset@dm_fixed_map_agent_goal.dataset
  - dm_fixed_map_agent_goal/train@dm_fixed_map_agent_goal.train
  - dm_fixed_map_agent_goal/eval@dm_fixed_map_agent_goal.eval
  - dm_fixed_map_agent_goal/model@dm_fixed_map_agent_goal.model
  - dm_fixed_map_agent_goal/datamodule@dm_fixed_map_agent_goal.datamodule
  - sim: base
  - _self_

dm_fixed_map_agent_goal:
  train:
    devices: 1
    track: True
    run_name: scenario_dreamer_dm_fixed_map_agent_goal_train
    wandb_project: critical_scene
