defaults:
- /datamodule/base@_here_
- _self_

_target_: datamodules.waymo.waymo_datamodule_dm_fixed_map_agent_goal.WaymoDataModuleDMFixedMapAgentGoal

train_batch_size: 256
val_batch_size: 256
dataset_cfg: null
